### ISSUE TITLE
Some data in grafana missing

### ISSUE THREAD

**Issue by litebito** [opc40772/pfsense-graylog#10]
Hi,

first of all, thank your efforts and info on setting up an easy way to get pfsense firewall log into a nice dashboard.

I've follow the instructions and also this thread : https://github.com/opc40772/pfsense-graylog/issues/5
Now I finally have some data in my grafana dashboard, but some graphs are still empty ("no datapoints" or "no data available")  : 
These graphs are : 
- Destination port by iface
- Top 10 port Destination Block 

and in the realtime logs by iface, source and destination portname are empty

regarding the portname, maybe this has something todo with: the lookup in the CSV ?

`java.lang.NullPointerException: null
        at org.graylog2.lookup.adapters.CSVFileDataAdapter.doRefresh(CSVFileDataAdapter.java:102) ~[graylog.jar:?]
        at org.graylog2.plugin.lookup.LookupDataAdapter.refresh(LookupDataAdapter.java:89) ~[graylog.jar:?]
        at org.graylog2.lookup.LookupDataAdapterRefreshService.lambda$schedule$0(LookupDataAdapterRefreshService.java:142) ~[graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

Anyone some advice or help?

**Comment by Makr91** [comment]
If you are having issues with the GeoIP settings look here:  https://github.com/opc40772/pfsense-graylog/issues/1
